# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:

  # main
- package-ecosystem: "nuget"
  directory: "/CreateMatrix"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

  # develop
- package-ecosystem: "nuget"
  directory: "/CreateMatrix"
  target-branch: "develop"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "develop"
  schedule:
    interval: "daily"
