blank_issues_enabled: false
contact_links:
  - name: Network Optix Support
    url: https://support.networkoptix.com/hc/en-us/community/topics
    about: Please report product issues to Network Optix.
