# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#name
name: "NxMeta-LSIO Pipeline"

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
      - develop

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  build:
    name: "Build Containers"
    runs-on: ubuntu-latest
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
    steps:
      # https://github.com/actions/checkout
      - name: "Checkout Code"
        uses: actions/checkout@v2
      # https://github.com/docker/setup-qemu-action
      - name: "Setup QEMU"
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v1
      # https://github.com/marketplace/actions/docker-login
      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: "Build and Push NxMeta-LSIO Latest"
        uses: docker/build-push-action@v2
        with:
          context: ./NxMeta-LSIO
          file: ./NxMeta-LSIO/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/nxmeta-lsio:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/nxmeta-lsio:4.1.0.32044
          build-args: |
            DOWNLOAD_VERSION=4.1.0.32044
            DOWNLOAD_URL=https://updates.networkoptix.com/metavms/32044/linux/metavms-server-4.1.0.32044-linux64-patch.deb
      - name: "Build and Push NxMeta-LSIO Stable"
        uses: docker/build-push-action@v2
        with:
          context: ./NxMeta-LSIO
          file: ./NxMeta-LSIO/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/nxmeta-lsio:stable
            ${{ secrets.DOCKER_HUB_USERNAME }}/nxmeta-lsio:4.1.0.32024
          build-args: |
            DOWNLOAD_VERSION=4.1.0.32024
            DOWNLOAD_URL=https://updates.networkoptix.com/metavms/32024/linux/metavms-server-4.1.0.32024-linux64-beta-prod.deb
