# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#name
name: GitHub Actions Test

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#on
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
      - develop

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobs
jobs:
  build:
    name: "Build Containers"
    runs-on: ubuntu-latest
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idsteps
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsrun
    steps:
    # https://github.com/actions/checkout
    - name: "Checkout Code"
      uses: actions/checkout@v2
    # https://github.com/marketplace/actions/docker-login
    - name: "Login to Docker Hub"
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: "Install M4"
      run: sudo apt install m4
    - name: "Run Make Create"
      run: make create
      working-directory: ./Make
    - name: "Run Make Build"
      run: make build
      working-directory: ./Make
